---
- name: Passer Debian d'une IP fixe à DHCP (nettoyage du fichier interfaces)
  hosts: all
  become: true
  gather_facts: true

  vars:
    interface_cible: "{{ ansible_default_ipv4.interface | default('eth0') }}"  # Interface par défaut
    # Pour forcer une interface spécifique, définis : interface_cible: "ens33"
    # Par défaut, on utilise la principale, sinon "eth0" si non détectée

  tasks:
    # Sauvegarde de l’ancien fichier (choisir l’emplacement selon tes besoins)
    - name: Sauvegarder /etc/network/interfaces
      ansible.builtin.copy:
        src: /etc/network/interfaces
        dest: /etc/network/interfaces.bak
        remote_src: true

    # Nettoyage complet : on ne garde que la partie loopback (lo)
    # On efface tout le reste du fichier pour éviter toute interférence
    - name: Remplacer /etc/network/interfaces par juste la boucle locale (lo)
      ansible.builtin.copy:
        dest: /etc/network/interfaces
        content: |
          auto lo
          iface lo inet loopback

    # On ajoute ensuite la configuration DHCP de l’interface ciblée
    - name: Ajouter la configuration DHCP pour {{ interface_cible }}
      ansible.builtin.lineinfile:
        path: /etc/network/interfaces
        insertafter: '^iface lo inet loopback'
        line: |
          auto {{ interface_cible }}
          iface {{ interface_cible }} inet dhcp
      notify: restart networking

  handlers:
    - name: restart networking
      ansible.builtin.service:
        name: networking
        state: restarted
