---
# **********************************************************
# Passer l’IP de statique à DHCP (Debian/Ubuntu, adapté pour esphome)
#
# À adapter :
# - interface_cible (ex : eth0, ens33, enp0s3 : vérifie avec `ip a`)
# - netplan_file (le fichier principal netplan, souvent /etc/netplan/00-installer-config.yaml)
# - nm_conn (nom de la connexion NetworkManager, vérifie avec `nmcli c`)
#
# Usage :
# ansible-playbook -i inventory.yml change-to-dhcp.yml
# **********************************************************

- name: Passer l’IP de statique à DHCP (Debian/Ubuntu)
  hosts: esphome  # 👈 Cible l’hôte défini dans ton inventory
  become: true    # Exécute en root
  vars:
    # À ADAPTER SELON TON ENVIRONNEMENT
    interface_cible: eth0                     # 🔧 Nom de l’interface à configurer (ATTENTION : Vérifie avec `ip a`)
    netplan_file: /etc/netplan/00-installer-config.yaml    # 🔧 Chemin du fichier netplan principal
    nm_conn: "Wired connection 1"             # 🔧 Nom de la connexion NetworkManager (voir `nmcli c`)

  # On désactive la collecte des facts pour aller plus vite (optionnel)
  gather_facts: false


  tasks:
    # -----------------------------------------------------------------------------
    # Détection de la méthode de gestion réseau
    # -----------------------------------------------------------------------------
    # On vérifie quelle méthode est utilisée : netplan, interfaces, NetworkManager

    - name: Vérifier si netplan est utilisé
      ansible.builtin.stat:
        path: "{{ netplan_file }}"
      register: netplan_stat       # Résultat dans netplan_stat

    - name: Vérifier si interfaces est utilisé
      ansible.builtin.stat:
        path: /etc/network/interfaces
      register: interfaces_stat    # Résultat dans interfaces_stat

    - name: Vérifier si NetworkManager est utilisé
      ansible.builtin.stat:
        path: "/etc/NetworkManager/system-connections/{{ nm_conn }}"
      register: networkmanager_stat # Résultat dans networkmanager_stat

    - name: Déterminer la méthode de gestion réseau
      ansible.builtin.set_fact:
        network_type: >-
          {% if netplan_stat.stat.exists %}
            netplan
          {% elif interfaces_stat.stat.exists %}
            interfaces
          {% elif networkmanager_stat.stat.exists %}
            networkmanager
          {% else %}
            unknown
          {% endif %}

    - name: Afficher la méthode détectée
      ansible.builtin.debug:
        msg: "Méthode de gestion réseau détectée : {{ network_type }}"


    # -----------------------------------------------------------------------------
    # Sauvegarde de la configuration actuelle
    # -----------------------------------------------------------------------------

    - name: Sauvegarder la configuration netplan
      ansible.builtin.copy:
        src: "{{ netplan_file }}"
        dest: "{{ netplan_file }}.bak"
        remote_src: true
      when: netplan_stat.stat.exists

    - name: Sauvegarder la configuration interfaces
      ansible.builtin.copy:
        src: /etc/network/interfaces
        dest: /etc/network/interfaces.bak
        remote_src: true
      when: interfaces_stat.stat.exists

    - name: Sauvegarder la configuration NetworkManager
      ansible.builtin.copy:
        src: "/etc/NetworkManager/system-connections/{{ nm_conn }}"
        dest: "/etc/NetworkManager/system-connections/{{ nm_conn }}.bak"
        remote_src: true
      when: networkmanager_stat.stat.exists


    # -----------------------------------------------------------------------------
    # Conversion vers DHCP selon la méthode détectée
    # -----------------------------------------------------------------------------

    - name: Passer en DHCP avec netplan
      ansible.builtin.blockinfile:
        path: "{{ netplan_file }}"
        backup: yes                  # Sauvegarde avant modification
        marker: "# {mark} ANSIBLE MANAGED BLOCK: Set interface DHCP"
        block: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              {{ interface_cible }}:
                dhcp4: true
                dhcp6: true
        insertafter: EOF             # Ajoute le bloc à la fin du fichier
      when: network_type == "netplan"

    - name: Passer en DHCP avec interfaces
      ansible.builtin.blockinfile:
        path: /etc/network/interfaces
        backup: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK: Set interface DHCP"
        block: |
          auto {{ interface_cible }}
          iface {{ interface_cible }} inet dhcp
        insertafter: EOF             # Ajoute la ligne à la fin du fichier
      when: network_type == "interfaces"

    - name: Passer en DHCP avec NetworkManager
      ansible.builtin.shell: |
        nmcli connection modify "{{ nm_conn }}" ipv4.method auto
        nmcli connection up "{{ nm_conn }}"
      when: network_type == "networkmanager"

    - name: Échec si aucune méthode connue n’est détectée
      ansible.builtin.fail:
        msg: "Aucune méthode de gestion réseau connue (netplan, interfaces, NetworkManager) n’a été détectée."
      when: network_type == "unknown"


    # -----------------------------------------------------------------------------
    # Appliquer la nouvelle configuration réseau
    # -----------------------------------------------------------------------------

    - name: Appliquer la configuration netplan (netplan apply)
      ansible.builtin.command: netplan apply
      when: network_type == "netplan"

    - name: Redémarrer le service networking (interfaces)
      ansible.builtin.service:
        name: networking
        state: restarted
      when: network_type == "interfaces"


    # -----------------------------------------------------------------------------
    # Récapitulatif final
    # -----------------------------------------------------------------------------

    - name: Message de confirmation
      ansible.builtin.debug:
        msg: "La configuration réseau a été modifiée pour passer de statique à DHCP sur {{ interface_cible }} (méthode : {{ network_type }})."

    # ⚠️ À la fin : vérifie que la connexion fonctionne toujours avant de te déconnecter !
    # Si tu utilises SSH pour administrer, prévois un accès de secours (console, KVM, etc.).
