---
# **********************************************************
# Playbook : Passer l’IP de statique à DHCP (Debian/Ubuntu)
# Détecte automatiquement la méthode réseau (ifupdown, netplan, NetworkManager)
# Applique la conversion adaptée, sauvegarde, redémarre le service, affiche le résultat
# Se connecte avec le compte ansible (doit avoir les droits sudo)
# **********************************************************

- name: Passer l’IP de statique à DHCP (détection automatique)
  hosts: esphome
  remote_user: ansible         # Utilisateur de connexion SSH (ajuster si besoin)
  gather_facts: false          # Pas besoin de collecter les facts réseaux ici

  vars:
    interface_cible: eth0      # 🔧 Nom de l’interface à configurer (vérifier avec ip a)
    netplan_file: /etc/netplan/00-installer-config.yaml   # 🔧 Fichier netplan par défaut
    nm_conn: "Wired connection 1"  # 🔧 Nom de connexion NetworkManager (voir nmcli c)

  tasks:

    # -------------------------------------------------------
    # 1. Détection automatique du type de gestion réseau
    # -------------------------------------------------------
    # On vérifie quelle méthode est utilisée sur le système cible :
    # - ifupdown (/etc/network/interfaces + networking.service)
    # - netplan (/etc/netplan/*.yaml + netplan apply)
    # - NetworkManager (/etc/NetworkManager/system-connections/)

    - name: Vérifier si ifupdown est utilisé (interfaces)
      ansible.builtin.stat:
        path: /etc/network/interfaces
      register: interfaces_stat

    - name: Vérifier si netplan est utilisé (netplan)
      ansible.builtin.stat:
        path: "{{ netplan_file }}"
      register: netplan_stat

    - name: Vérifier si NetworkManager est utilisé (system-connections)
      ansible.builtin.stat:
        path: "/etc/NetworkManager/system-connections/{{ nm_conn }}"
      register: networkmanager_stat

    - name: Déterminer la méthode active
      ansible.builtin.set_fact:
        network_type: >-
          {% if netplan_stat.stat.exists %}
            netplan
          {% elif networkmanager_stat.stat.exists %}
            networkmanager
          {% elif interfaces_stat.stat.exists %}
            interfaces
          {% else %}
            unknown
          {% endif %}

    - name: Afficher la méthode détectée
      ansible.builtin.debug:
        msg: "Méthode de gestion réseau détectée : {{ network_type }}"


    # -------------------------------------------------------
    # 2. Sauvegarde de la configuration actuelle
    # -------------------------------------------------------
    - name: Sauvegarder la configuration actuelle (interfaces)
      ansible.builtin.copy:
        src: /etc/network/interfaces
        dest: /etc/network/interfaces.bak
        remote_src: true
      become: true
      when: network_type == "interfaces"

    - name: Sauvegarder la configuration actuelle (netplan)
      ansible.builtin.copy:
        src: "{{ netplan_file }}"
        dest: "{{ netplan_file }}.bak"
        remote_src: true
      become: true
      when: network_type == "netplan"

    - name: Sauvegarder la configuration actuelle (NetworkManager
